config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'menus/show'
  end
  # 顧客
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 顧客ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'  #ゲストログインurl
  end

  # 管理者
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"

    patch '/customers/:id/withdraw' => 'customers#withdraw', as: "withdraw"
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: "unsubscribe"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    get 'menus/:id/index' => 'menus#index', as: "index"
    resources :menus, only: [:new, :create, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: "homes#top"
    get 'customers/member' => 'customers#member'
    get '/customers/mypage' => 'customers#show'
    resources :customers, only: [:edit, :update]
    resources :genres, only: [:index, :show]
    resources :menus, only: [:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/_footer.html.erb
<!--フッターの共通化-->
</main>
<footer>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="nav-item"><%= link_to "ジャンル", admin_genres_path, class: "btn btn-sm btn-outline-secondary ml-3" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</footer>

app/views/admin/_header.html.erb
<!--ヘッダーの共通化-->
<header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <%= link_to admin_root_path do %>
          <i class="fas fa-house-user"></i>
        <% end %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item"><%= link_to "会員一覧",  admin_customers_path, class: "btn btn-sm btn-outline-secondary ml-3" %></li>
              <li class="nav-item"><%= link_to "ログアウト",  destroy_admin_session_path, method: :delete, class: "btn btn-sm btn-outline-secondary ml-3" %></li>
            <% else %>
              <li class="nav-item"><%= link_to "会員一覧",  admin_customers_path, class: "btn btn-sm btn-outline-secondary ml-3" %></li>
              <li class="nav-item"><%= link_to "ログイン", new_admin_session_path, class: "btn btn-sm btn-outline-secondary ml-3" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
</header>
<main class="pb-4 shadow-sm">

app/views/admin/_list.html.erb
<!--会員一覧画面-->
<!--Topページと会員一覧画面の共通化-->
<%= render 'admin/header' %>

<h5 class="mt-4 ml-3">会員一覧</h5>

<table class="table mt-4">
  <thead class="table-secondary">
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td>
        <% if admin_signed_in? %>
          <%= link_to  admin_customer_path(customer.id) do %>
            <%= customer.last_name %><%= customer.first_name %>
          <% end %>

        <% else %>
          <%= customer.last_name %><%= customer.first_name %>
        <% end %>
      </td>
      <td><%= customer.email %></td>
      <td>
         <% if customer.is_deleted == false %>
          <p class="text-success font-weight-bold">有効</p>
        <% else %>
          <p class="text-secondary font-weight-bold">退会</p>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @customers %>

<%= render 'admin/footer' %>