config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'menus/show'
  end
  # 顧客
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 顧客ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'  #ゲストログインurl
  end

  # 管理者
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"

    patch '/customers/:id/withdraw' => 'customers#withdraw', as: "withdraw"
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: "unsubscribe"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    get 'menus/:id/index' => 'menus#index', as: "index"
    resources :menus, only: [:new, :create, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: "homes#top"
    get 'customers/member' => 'customers#member'
    get '/customers/mypage' => 'customers#show'
    resources :customers, only: [:edit, :update]
    resources :genres, only: [:index, :show]
    resources :menus, only: [:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum sex: { man: 0, woman: 1 }

  has_one_attached :profile_image
  
  #新規会員登録及び会員編集バリデーション
  validates :age, numericality: { only_integer: true }

  # QRコードの名前の関する情報
  def full_name
    last_name + first_name
  end

  # 画像の有無判定
  def get_profile_image(width, height, center)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  # ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = 'ゲスト'
      customer.first_name = '会員'
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def unsubscribe
    @customer = Customer.find(params[:id])
  end

  def withdraw
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
    redirect_to admin_root_path
  end


  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

   # ストロングパラメータ
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :sex, :year_birth, :age, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<!--会員情報編集画面-->
<%= render 'admin/header' %>

<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-12">
      <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
    </div>
    <div class="mt-4">
      <%= form_with model: @customer, url:admin_customer_path, method: :patch do |f| %>
        <div class="row">
          <div class="col-md-4">
            <label>氏名</label>
          </div>
          <div class="col-md-4" >
            <%= f.text_field :last_name, style: "width:150px" %>
          </div>
          <div class="col-md-4">
            <%= f.text_field :first_name, style: "width:150px" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <label>フリガナ</label>
          </div>
          <div class="col-md-4">
            <%= f.text_field :last_name_kana, style: "width:150px" %>
          </div>
          <div class="col-md-4">
            <%= f.text_field :first_name_kana, style: "width:150px" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <label>性別</label>
          </div>
          <div class="col-md-8">
            <%= f.radio_button :sex, "man" %>
            <%= f.label :sex, "男性", value: "man" %>
            <%= f.radio_button :sex, "woman" %>
            <%= f.label :sex, "女性", value: "woman" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <%= f.label :year_birth, '生年月日' %>
          </div>
          <div class="col-md-8">
            <%= f.date_select :year_birth,start_year: 1930, end_year: (Time.now.year - 15), default: Date.new(1989, 1, 1) %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <label>年齢</label>
          </div>
          <div class="col-md-8">
            <%= f.text_field :age, style: "width:50px" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <label>郵便番号</label>
          </div>
          <div class="col-md-8">
            <%= f.text_field :postal_code, style: "width:200px" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <label>住所</label>
          </div>
          <div class="col-md-8">
            <%= f.text_field :address, style: "width:400px" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4">
            <label>電話番号</label>
          </div>
          <div class="col-md-8">
            <%= f.text_field :telephone_number, style: "width:200px" %>
          </div>
        </div>

         <div class="row">
          <div class="col-md-4">
            <label>メールアドレス</label>
          </div>
          <div class="col-md-8">
            <%= f.text_field :email, style: "width:400px" %>
          </div>
        </div>

         <div class="row">
          <div class="col-md-4">
            <label>会員ステータス</label>
          </div>
          <div class="col-md-8">
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted_false, "有効" %>

            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted_true, "退会" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= f.submit '変更を保存', class: "btn btn-success" %>
          </div>
          <div class="col-md-6">
            <%= link_to "退会する",admin_unsubscribe_path(@customer.id), class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render 'admin/footer' %>

app/views/admin/customers/index.html.erb
<!--会員一覧-->
<%= render 'admin/list' %>

app/views/admin/customers/show.html.erb
<!--会員情報詳細画面-->
<%= render 'admin/header' %>

<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-12">
      <h5 class="mt-4 mb-3"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報</h5>

      <div class="row">
        <div class="col-md-4">
          <label>会員ID</label>
        </div>
        <div class="col-md-8">
          <%= @customer.id %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <label>氏名</label>
        </div>
        <div class="col-md-8">
          <%= @customer.last_name %><%= @customer.first_name %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>フリガナ</label>
        </div>
        <div class="col-md-8">
          <%= @customer.last_name_kana %><%= @customer.first_name_kana %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>性別</label>
        </div>
        <div class="col-md-8">
          <%= @customer.sex_i18n %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>生年月日</label>
        </div>
        <div class="col-md-8">
          <%= @customer.year_birth %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>年齢</label>
        </div>
        <div class="col-md-8">
          <%= @customer.age %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>郵便番号</label>
        </div>
        <div class="col-md-8">
          <%= @customer.postal_code %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>住所</label>
        </div>
        <div class="col-md-8">
          <%= @customer.address %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>電話番号</label>
        </div>
        <div class="col-md-8">
          <%= @customer.telephone_number %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>メールアドレス</label>
        </div>
        <div class="col-md-8">
          <%= @customer.email %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>会員ステータス</label>
        </div>
        <div class="col-md-8">
          <% if @customer.is_deleted == false %>
            <p class="text-success font-weight-bold">有効</p>
          <% else %>
            <p class="text-secondary font-weight-bold">退会</p>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-2 offset-md-2">
          <%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
        </div>
        <div class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>

<%= render 'admin/footer' %>

app/views/admin/customers/unsubscribe.html.erb
<!--退会画面-->
<style>
  main{
    height: 100%;
  }
</style>

<%= render 'public/header' %>

<p id="notice"></p>

<div class="row h-100 d-flex text-center align-items-center">
  <div class="w-100">
    <h4 class="mb-5"><strong>本当に退会しますか？</strong></h4>
    <p>
      退会すると、会員登録情報や<br />
      これまでの購入履歴が閲覧できなくなります。<br />
      退会する場合は「退会をする」をクリックしてください。
    </p>
    <%= link_to "退会しない", admin_root_path, class: "btn btn-primary mr-3" %>
    <%= link_to "退会する", admin_withdraw_path(@customer.id), method: :patch, data: { confirm: "本当に退会しますか？" }, class: "btn btn-danger" %>
  </div>
</div>

<%= render 'public/footer' %>