config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'menus/show'
  end
  # 顧客
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 顧客ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'  #ゲストログインurl
  end

  # 管理者
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"

    patch '/customers/:id/withdraw' => 'customers#withdraw', as: "withdraw"
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: "unsubscribe"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    get 'menus/:id/index' => 'menus#index', as: "index"
    resources :menus, only: [:new, :create, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: "homes#top"
    get 'customers/member' => 'customers#member'
    get '/customers/mypage' => 'customers#show'
    resources :customers, only: [:edit, :update]
    resources :genres, only: [:index, :show]
    resources :menus, only: [:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :menus, dependent: :destroy
  
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!, except: [:top]

  def index
    @genre = Genre.new
    @genres = Genre.all.page(params[:page]).per(5)
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre= Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end


  private

   # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<!--ジャンル名編集画面-->
<%= render 'admin/header' %>

<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-12">
      <h4>ジャンル編集</h4>
      <%= form_with model: @genre, url:admin_genre_path, method: :patch do |f| %>
        <div class="row">
          <div class="col-2 pb-3">
            <p>ジャンル名</p>
          </div>
          <div class="col-3 pb-3">
            <%= f.text_field :name %>
          </div>
          <div class="col-7 pb-3">
             <%= f.submit '変更を保存', class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render 'admin/footer' %>

app/views/admin/genres/index.html.erb
<!--ジャンル一覧・追加画面-->
<%= render 'admin/header' %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-7 mb-4">
        <h4>ジャンル一覧・追加</h4>
        <%= form_with model: @genre, url:admin_genres_path do |f| %>
          <div class="row mt-4">
            <div class="col-3 pb-3">
              <p>ジャンル名</p>
            </div>
            <div class="col-7 pb-3">
              <%= f.text_field :name %>
            </div>
            <div class="col-1 pb-3">
              <%= f.submit '新規登録', class: "btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>
        <!--ジャンル一覧-->
      <div class="row">
        <div class="col-10">
          <ul class="list-group">
            <li class="list-group-item">
              <div class="row">
                <div class="col-11 pb-3">
                  <h5>ジャンル一覧</h5>
                </div>
                <div class="col-1 pb-3"></div>
              </div>
            </li>
            <% @genres.each do |genre| %>
              <li class="list-group-item">
               <div class="row">
                  <div class="col-3 pb-3">
                    <%= genre.name %>
                  </div>
                  <div class="col-4 pb-3">
                    <%= link_to "メニュー一覧", admin_index_path(genre.id), class: "btn btn-primary" %>
                  </div>
                  <div class="col-3 pb-3">
                    <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %>
                  </div>
                  <div class="col-2 pb-3">
                    <%= link_to "削除", admin_genre_path(genre.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <%= paginate @genres %>
    </div>
  </div>
</div>

<%= render 'admin/footer' %>